### ISSUE TITLE
[error] You tried to start Browsersync twice! 

### ISSUE THREAD

**Issue by mnemanja** [alferov/generator-angular-gulp-browserify#1]
I get this error when I run 'dev test'
[error] You tried to start Browsersync twice! To create multiple instances, use browserSync.create().init()

Why does it try to load it twice?

**Comment by alferov** [comment]
Could you reinstall the package `npm install -g generator-angular-gulp-browserify` an try it again?

**Comment by mnemanja** [comment]
That have helped. 
Nice. Good job.
