### ISSUE TITLE
code ELIFECYCLE error upon starting protractor

### ISSUE THREAD

**Issue by mnemanja** [alferov/generator-angular-gulp-browserify#2]
npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7
    npm ERR! code ELIFECYCLE
    npm ERR! ttee@ protractor: `protractor test/protractor.conf.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ttee@ protractor script 'protractor test/protractor.conf.js'.

Most probably it's exactly the same as here. https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/101

**Comment by alferov** [comment]
Hey @mnemanja, have you resolved this issue?

**Comment by mnemanja** [comment]
It works now, but unfortunately I'm not certain what fixed it...
