### ISSUE TITLE
Babel deoptimized the styling the styling - template.js more then 100kb

### ISSUE THREAD

**Issue by mnemanja** [alferov/generator-angular-gulp-browserify#4]
I've been searching on how to deal with this, but haven't managed to find a solution.

    [BABEL] Note: The code generator has deoptimised the styling of "PATH/templates.js" as it exceeds the max of "100KB".

Currently I don't know what problem it produces (performance, or something else). It appears twice in the log when I run any of the tasks.

**Comment by alferov** [comment]
Hmm, try to change this [line](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js#L41) to:
``` { 'name':babelify, 'options': { 'compact': 'true' }},```

**Comment by mnemanja** [comment]
That works, great. Thanks! :)

**Comment by mnemanja** [comment]
That works, great. Thanks! :)
