### ISSUE TITLE
Error: Cannot find module 'gulp-traceur'

### ISSUE THREAD

**Issue by karneaud** [alferov/generator-angular-gulp-browserify#6]
Using the latest node, npm, gulp I ran into the following error on `gulp serve`

> module.js:338
>     throw err;
>           ^
> Error: Cannot find module 'gulp-traceur'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:278:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt/gulpfile.js:3:15)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>

**Comment by alferov** [comment]
gulp-traceur? :scream:
Let me check it

**Comment by alferov** [comment]
It seems like you worked with a different generator:
1) There is no `serve` task in the existent workflow (and never was), `gulp dev` does the job.
2) Traceur has never been used.
You can see a list of installed generators by running `yo --generators`.
